name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-Image:
    name: Build image
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag torrent-search-spring:latest
      
  Redploy-Container:
    name: Start Container
    runs-on: self-hosted
    
    steps:
    - name: Execute script to redploy container
      run: /home/phanijsp/docker-run/init.sh
