name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-Deploy:
    name: Build and deploy
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build . --file Dockerfile --tag torrent-search-spring:latest
    - name: Redploy container
      run: /home/phanijsp/docker-run/init.sh
    
